version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    environment:
      CLICKHOUSE_DB: test
      CLICKHOUSE_USER: test
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_PASSWORD: test
    ports:
      - "9000:9000"
      - "8123:8123"
    restart: unless-stopped
    volumes:
      - clickhouse-data:/var/lib/clickhouse

volumes:
  clickhouse-data: