version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  clickhouse-server:
    image: clickhouse/clickhouse-server
    environment:
      CLICKHOUSE_DB: test
      CLICKHOUSE_USER: test
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_PASSWORD: test
    ports:
      - "9000:9000"
      - "8123:8123"
    restart: unless-stopped
    volumes:
      - clickhouse-data:/var/lib/clickhouse
  zio-graphql-stack:
    image: zio-graphql-stack:0.1.0-SNAPSHOT
    profiles:
      - app
    ports:
      - "8080:8080"
    environment:
      CH_JDBC_URL: "jdbc:clickhouse://host.docker.internal:8123/test"
      REDIS_URL: "http://host.docker.internal:6379"

volumes:
  clickhouse-data: