version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.47
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    restart: unless-stopped
  redis:
    image: redis
    ports:
      - "6379:6379"
  clickhouse-server:
    image: clickhouse/clickhouse-server
    environment:
      CLICKHOUSE_DB: test
      CLICKHOUSE_USER: test
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_PASSWORD: test
    ports:
      - "9000:9000"
      - "8123:8123"
    restart: unless-stopped
    volumes:
      - clickhouse-data:/var/lib/clickhouse
  zio-graphql-stack:
    image: zio-graphql-stack:0.1.0-SNAPSHOT
    profiles:
      - app
    ports:
      - "8080:8080"
    environment:
      CH_JDBC_URL: "jdbc:clickhouse://host.docker.internal:8123/test"
      REDIS_URL: "http://host.docker.internal:6379"
      TRACING_URL: "http://host.docker.internal:4317"

volumes:
  clickhouse-data: